#!/bin/bash

source /usr/local/JSBach/conf/variables.conf


while read ordre
do
	if [[ -n $ordre ]]; then
		ordre=$(echo "$ordre" | tr -d '\r')
		
		Comando=$(echo $ordre| awk '{print $1}') 
		Arguments=$(echo $ordre| awk '{for (i=2; i<=NF; ++i)  printf $i " " }') 
		
		# Debug logging
		echo "Recibido: [$ordre] | Comando: [$Comando] | Args: [$Arguments]" >> /tmp/scr_cli.log
				
		case "$Comando" in
			"enrutar")  
			    $DIR/$PROJECTE/$DIR_SCRIPTS/enrutar $Arguments
			    ;;
			"ifwan")
			    $DIR/$PROJECTE/$DIR_SCRIPTS/ifwan $Arguments
			    ;;
			"bridge")
			    $DIR/$PROJECTE/$DIR_SCRIPTS/bridge $Arguments
			    ;;			    
			"tallafocs")
			    $DIR/$PROJECTE/$DIR_SCRIPTS/tallafocs $Arguments
			    ;;	
			"dmz")
			    $DIR/$PROJECTE/$DIR_SCRIPTS/dmz $Arguments
			    ;;	
			"wifi")
			    $DIR/$PROJECTE/$DIR_SCRIPTS/wifi $Arguments
			    ;;
			"dhcp")
			    $DIR/$PROJECTE/$DIR_SCRIPTS/dhcp $Arguments
			    ;;
			"portal_captiu")
			    $DIR/$PROJECTE/$DIR_SCRIPTS/portal_captiu.sh $Arguments
			    ;;
			"switch-scripts.sh")
			    $DIR/$PROJECTE/$DIR_SCRIPTS/switch-scripts.sh $Arguments
			    ;;
			*) 
			    echo "CLI Error en l'argument $Comando $Arguments"
			    ;;
		esac	
	fi
	
	echo "final"
done;
